spring:
  application:
    name: Training_Management_System
  datasource:
    url: jdbc:mariadb://localhost:3305/tms_prototype_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/master-changelog.xml
    contexts: development
    default-schema: tms_prototype_db
    liquibase-schema: tms_prototype_db
    drop-first: false

server:
  port: 8080
